name: ${PROJECT_NAME}

services:
  pg-build:
    build: .
    image: ${PROJECT_NAME}_pg-build:${IMAGE_TAG}
    container_name: ${PROJECT_NAME}_pg-build
    hostname: ${PROJECT_NAME}_pg-build
    restart: unless-stopped
    tty: true
    stdin_open: true
    environment:
      - TZ=${TZ}
    volumes:
      - ./:/workspace
      - ./pgsql:/usr/local/pgsql
      - pgdata:/var/lib/postgresql/data
      - ./dotfiles:/workspace/dotfiles
    working_dir: /workspace
    command: ["/usr/bin/zsh","-l"]                   # inicia zsh como shell padr√£o
    networks:
      - pg-net

networks:
  pg-net:
    driver: bridge

volumes:
  pgdata: