name: ${PROJECT_NAME}

services:
  pg-build:
    build: .
    image: ${PROJECT_NAME}_pg-build:${IMAGE_TAG}
    container_name: ${PROJECT_NAME}_pg-build
    hostname: pg-build
    restart: unless-stopped
    tty: true
    stdin_open: true
    environment:
      - TZ=${TZ}
    volumes:
      - ./:/workspace
      - pgdata:/var/lib/postgresql/data
      - ./dotfiles:/workspace/dotfiles
    working_dir: /workspace
    networks:
      - pg-net
    command: ["/usr/bin/zsh", "-l"]

networks:
  pg-net:
    driver: bridge

volumes:
  pgdata: