name: ${PROJECT_NAME}

services:
  pg-build:
    build: .
    image: ${PROJECT_NAME}-pg-build:${IMAGE_TAG}
    container_name: ${PROJECT_NAME}-pg-build
    hostname: ${PROJECT_NAME}-pg-build
    restart: unless-stopped
    tty: true
    stdin_open: true
    volumes:
      - ./:/workspace
      - ./pgsql:/usr/local/pgsql
      - pgdata:/var/lib/postgresql/data
    working_dir: /workspace
    command: bash
    networks:
      - containet

networks:
  containet:
    driver: bridge

volumes:
  pgdata: